import tweepy
import logging
from config import create_api
import time
import random

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger()

acx_articles = [
    "https://astralcodexten.substack.com/p/open-thread-1975",
    "https://astralcodexten.substack.com/p/apply-for-an-acx-grant",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-orban",
    "https://astralcodexten.substack.com/p/secrets-of-the-great-families",
    "https://astralcodexten.substack.com/p/model-city-monday-11821",
    "https://astralcodexten.substack.com/p/open-thread-197",
    "https://astralcodexten.substack.com/p/open-thread-1965",
    "https://astralcodexten.substack.com/p/dictator-book-club-orban",
    "https://astralcodexten.substack.com/p/non-cognitive-skills-for-educational",
    "https://astralcodexten.substack.com/p/mantic-monday-11121",
    "https://astralcodexten.substack.com/p/open-thread-196",
    "https://astralcodexten.substack.com/p/jhanas-and-the-dark-room-problem",
    "https://astralcodexten.substack.com/p/learn-british-english-with-acx",
    "https://astralcodexten.substack.com/p/epistemic-minor-leagues",
    "https://astralcodexten.substack.com/p/open-thread-195-cambridgeedinburgh",
    "https://astralcodexten.substack.com/p/chilling-effects",
    "https://astralcodexten.substack.com/p/open-thread-194-londonoxford-meetups",
    "https://astralcodexten.substack.com/p/links-for-october",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-kids",
    "https://astralcodexten.substack.com/p/please-dont-give-up-on-having-kids",
    "https://astralcodexten.substack.com/p/learn-german-with-acx",
    "https://astralcodexten.substack.com/p/open-thread-192-berlinparis-meetups",
    "https://astralcodexten.substack.com/p/classifieds-thread-102021",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-modern",
    "https://astralcodexten.substack.com/p/open-thread-192-viennaprague-meetups",
    "https://astralcodexten.substack.com/p/learn-spanish-with-acx",
    "https://astralcodexten.substack.com/p/open-thread-1915",
    "https://astralcodexten.substack.com/p/book-review-the-scout-mindset",
    "https://astralcodexten.substack.com/p/open-thread-191-madridzurich-meetups",
    "https://astralcodexten.substack.com/p/whither-tartaria",
    "https://astralcodexten.substack.com/p/learn-portuguese-with-acx",
    "https://astralcodexten.substack.com/p/links-for-september",
    "https://astralcodexten.substack.com/p/open-thread-190",
    "https://astralcodexten.substack.com/p/lisbon-meetup-this-saturday",
    "https://astralcodexten.substack.com/p/book-review-the-revolt-of-the-public",
    "https://astralcodexten.substack.com/p/open-thread-1895",
    "https://astralcodexten.substack.com/p/book-review-modi-a-political-biography",
    "https://astralcodexten.substack.com/p/open-thread-189",
    "https://astralcodexten.substack.com/p/washington-dc-meetup-this-saturday",
    "https://astralcodexten.substack.com/p/open-thread-1885",
    "https://astralcodexten.substack.com/p/the-unbearable-semiheaviness-of-being",
    "https://astralcodexten.substack.com/p/too-good-to-check-a-play-in-three",
    "https://astralcodexten.substack.com/p/new-york-meetup-this-monday",
    "https://astralcodexten.substack.com/p/open-thread-188",
    "https://astralcodexten.substack.com/p/boston-meetup-this-sunday",
    "https://astralcodexten.substack.com/p/long-covid-much-more-than-you-wanted",
    "https://astralcodexten.substack.com/p/open-thread-1875",
    "https://astralcodexten.substack.com/p/peer-review-long-covid-much-more",
    "https://astralcodexten.substack.com/p/on-hreha-on-behavioral-economics",
    "https://astralcodexten.substack.com/p/open-thread-187",
    "https://astralcodexten.substack.com/p/berkeley-meetup-this-saturday",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-missing",
    "https://astralcodexten.substack.com/p/if-youre-so-smart-why-arent-you-governor",
    "https://astralcodexten.substack.com/p/carbon-costs-quantified",
    "https://astralcodexten.substack.com/p/meetups-everywhere-2021-times-and",
    "https://astralcodexten.substack.com/p/open-thread-186",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-aducanumab",
    "https://astralcodexten.substack.com/p/peer-review-request-carbon-costs",
    "https://astralcodexten.substack.com/p/open-thread-1855",
    "https://astralcodexten.substack.com/p/links-for-august",
    "https://astralcodexten.substack.com/p/kids-can-recover-from-missing-even",
    "https://astralcodexten.substack.com/p/open-thread-185",
    "https://astralcodexten.substack.com/p/blindness-schizophrenia-and-autism",
    "https://astralcodexten.substack.com/p/contra-hanania-on-partisanship",
    "https://astralcodexten.substack.com/p/open-thread-1845",
    "https://astralcodexten.substack.com/p/classifieds-thread-82021",
    "https://astralcodexten.substack.com/p/outdoor-careful-meetups-everywhere",
    "https://astralcodexten.substack.com/p/eight-hundred-slightly-poisoned-word",
    "https://astralcodexten.substack.com/p/open-thread-184",
    "https://astralcodexten.substack.com/p/contra-drum-on-the-fish-oil-story",
    "https://astralcodexten.substack.com/p/open-thread-1835",
    "https://astralcodexten.substack.com/p/details-of-the-infant-fish-oil-story",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-acemoglu",
    "https://astralcodexten.substack.com/p/adumbrations-of-aducanumab",
    "https://astralcodexten.substack.com/p/what-should-we-make-of-sasha-chapins",
    "https://astralcodexten.substack.com/p/model-city-monday-8221",
    "https://astralcodexten.substack.com/p/open-thread-183",
    "https://astralcodexten.substack.com/p/updated-look-at-long-term-ai-risks",
    "https://astralcodexten.substack.com/p/when-does-worrying-about-things-trade",
    "https://astralcodexten.substack.com/p/contra-acemoglu-onoh-god-were-doing",
    "https://astralcodexten.substack.com/p/mantic-monday-726",
    "https://astralcodexten.substack.com/p/open-thread-182",
    "https://astralcodexten.substack.com/p/links-for-july",
    "https://astralcodexten.substack.com/p/open-thread-1815",
    "https://astralcodexten.substack.com/p/things-i-learned-writing-the-lockdown",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-crazy",
    "https://astralcodexten.substack.com/p/peer-review-request-ketamine",
    "https://astralcodexten.substack.com/p/open-thread-181",
    "https://astralcodexten.substack.com/p/please-take-the-reader-survey",
    "https://astralcodexten.substack.com/p/open-thread-1805",
    "https://astralcodexten.substack.com/p/book-review-crazy-like-us",
    "https://astralcodexten.substack.com/p/reader-survey-final-check-in",
    "https://astralcodexten.substack.com/p/use-prediction-markets-to-fund-investigative",
    "https://astralcodexten.substack.com/p/open-thread-180",
    "https://astralcodexten.substack.com/p/book-review-contest-winners",
    "https://astralcodexten.substack.com/p/open-thread-1795",
    "https://astralcodexten.substack.com/p/is-this-predictive-coding",
    "https://astralcodexten.substack.com/p/lockdown-effectiveness-much-more",
    "https://astralcodexten.substack.com/p/model-city-monday",
    "https://astralcodexten.substack.com/p/open-thread-179",
    "https://astralcodexten.substack.com/p/open-thread-1785",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-how",
    "https://astralcodexten.substack.com/p/welcome-polygenically-screened-babies",
    "https://astralcodexten.substack.com/p/book-review-how-asia-works",
    "https://astralcodexten.substack.com/p/open-thread-178",
    "https://astralcodexten.substack.com/p/open-thread-1775",
    "https://astralcodexten.substack.com/p/acx-reader-research-survey-call-for",
    "https://astralcodexten.substack.com/p/perpendicular-lives",
    "https://astralcodexten.substack.com/p/links-for-june",
    "https://astralcodexten.substack.com/p/mantic-monday-62121",
    "https://astralcodexten.substack.com/p/open-thread-177",
    "https://astralcodexten.substack.com/p/vote-in-the-book-review-contest",
    "https://astralcodexten.substack.com/p/your-book-review-plagues-and-peoples",
    "https://astralcodexten.substack.com/p/peer-review-lockdown-effectiveness",
    "https://astralcodexten.substack.com/p/open-thread-1765",
    "https://astralcodexten.substack.com/p/on-cerebralab-on-nuttcarhart-harris",
    "https://astralcodexten.substack.com/p/contra-smith-on-jewish-selective",
    "https://astralcodexten.substack.com/p/open-thread-176",
    "https://astralcodexten.substack.com/p/your-book-review-how-children-fail",
    "https://astralcodexten.substack.com/p/open-thread-1755",
    "https://astralcodexten.substack.com/p/your-book-review-down-and-out-in",
    "https://astralcodexten.substack.com/p/drug-users-use-a-lot-of-drugs",
    "https://astralcodexten.substack.com/p/i-will-not-eat-the-bugs",
    "https://astralcodexten.substack.com/p/instead-of-pledging-to-change-the",
    "https://astralcodexten.substack.com/p/open-thread-175",
    "https://astralcodexten.substack.com/p/your-book-review-wheres-my-flying",
    "https://astralcodexten.substack.com/p/your-book-review-the-collapse-of",
    "https://astralcodexten.substack.com/p/open-thread-1745",
    "https://astralcodexten.substack.com/p/you-have-a-terrible-track-record",
    "https://astralcodexten.substack.com/p/moral-costs-of-chicken-vs-beef",
    "https://astralcodexten.substack.com/p/what-do-treatments-for-accelerated",
    "https://astralcodexten.substack.com/p/open-thread-174",
    "https://astralcodexten.substack.com/p/your-book-review-humankind",
    "https://astralcodexten.substack.com/p/covid-suicides-much-more-than-you",
    "https://astralcodexten.substack.com/p/open-thread-1735",
    "https://astralcodexten.substack.com/p/reflections-on-greed-being-made-of",
    "https://astralcodexten.substack.com/p/peer-review-request-depression",
    "https://astralcodexten.substack.com/p/book-review-arabian-nights",
    "https://astralcodexten.substack.com/p/open-thread-173",
    "https://astralcodexten.substack.com/p/your-book-review-the-accidental-superpower",
    "https://astralcodexten.substack.com/p/links-for-may",
    "https://astralcodexten.substack.com/p/the-coldness-of-karen",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-culture",
    "https://astralcodexten.substack.com/p/open-thread-172",
    "https://astralcodexten.substack.com/p/your-book-review-addiction-by-design",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-cbt",
    "https://astralcodexten.substack.com/p/welcome-to-the-terrible-world-of",
    "https://astralcodexten.substack.com/p/theses-on-the-current-moment",
    "https://astralcodexten.substack.com/p/the-rise-and-fall-of-online-culture",
    "https://astralcodexten.substack.com/p/open-thread-171",
    "https://astralcodexten.substack.com/p/my-favorite-icd-10-codes",
    "https://astralcodexten.substack.com/p/your-book-review-the-years-of-lyndon",
    "https://astralcodexten.substack.com/p/your-book-review-through-the-eye",
    "https://astralcodexten.substack.com/p/why-is-it-hard-to-acknowledge-preferences",
    "https://astralcodexten.substack.com/p/book-review-a-brief-history-of-neoliberalism",
    "https://astralcodexten.substack.com/p/if-you-can-be-bad-you-can-also-be",
    "https://astralcodexten.substack.com/p/open-thread-170",
    "https://astralcodexten.substack.com/p/your-book-review-the-wizard-and-the",
    "https://astralcodexten.substack.com/p/your-book-review-double-fold",
    "https://astralcodexten.substack.com/p/nootropics-survey-2020-results",
    "https://astralcodexten.substack.com/p/verses-written-on-the-occasion-of",
    "https://astralcodexten.substack.com/p/mantic-monday-predictions-for-2021",
    "https://astralcodexten.substack.com/p/open-thread-169",
    "https://astralcodexten.substack.com/p/your-book-review-why-buddhism-is",
    "https://astralcodexten.substack.com/p/your-book-review-are-we-smart-enough",
    "https://astralcodexten.substack.com/p/book-review-global-economic-history",
    "https://astralcodexten.substack.com/p/no-really-why-are-so-many-christians",
    "https://astralcodexten.substack.com/p/mantic-monday-grading-my-trump-predictions",
    "https://astralcodexten.substack.com/p/open-thread-168",
    "https://astralcodexten.substack.com/p/georgist-cartoons-of-the-late-19thearly",
    "https://astralcodexten.substack.com/p/your-book-review-progress-and-poverty",
    "https://astralcodexten.substack.com/p/prospectus-on-prospera",
    "https://astralcodexten.substack.com/p/link-unifying-predictive-coding-with",
    "https://astralcodexten.substack.com/p/links-for-april",
    "https://astralcodexten.substack.com/p/from-the-rejects-pile-catch-22",
    "https://astralcodexten.substack.com/p/open-thread-167",
    "https://astralcodexten.substack.com/p/your-book-review-on-the-natural-faculties",
    "https://astralcodexten.substack.com/p/your-book-review-order-without-law",
    "https://astralcodexten.substack.com/p/metis-and-bodybuilders",
    "https://astralcodexten.substack.com/p/two-unexpected-multiple-hypothesis",
    "https://astralcodexten.substack.com/p/2020-predictions-calibration-results",
    "https://astralcodexten.substack.com/p/open-thread-166",
    "https://astralcodexten.substack.com/p/ambidexterity-and-cognitive-closure",
    "https://astralcodexten.substack.com/p/oh-the-places-youll-go-when-trying",
    "https://astralcodexten.substack.com/p/open-thread-165",
    "https://astralcodexten.substack.com/p/ask-me-anything",
    "https://astralcodexten.substack.com/p/towards-a-bayesian-theory-of-willpower",
    "https://astralcodexten.substack.com/p/more-antifragile-diversity-libertarianism",
    "https://astralcodexten.substack.com/p/book-review-antifragile",
    "https://astralcodexten.substack.com/p/adding-my-data-point-to-the-discussion",
    "https://astralcodexten.substack.com/p/open-thread-164",
    "https://astralcodexten.substack.com/p/book-review-the-new-sultan",
    "https://astralcodexten.substack.com/p/sleep-is-the-mate-of-death",
    "https://astralcodexten.substack.com/p/mantic-monday-mantic-matt-y",
    "https://astralcodexten.substack.com/p/open-thread-163",
    "https://astralcodexten.substack.com/p/richard-nixon-vs-cool",
    "https://astralcodexten.substack.com/p/trapped-priors-as-a-basic-problem",
    "https://astralcodexten.substack.com/p/the-consequences-of-radical-reform",
    "https://astralcodexten.substack.com/p/open-thread-162",
    "https://astralcodexten.substack.com/p/theyre-made-out-of-meta",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-class",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-march",
    "https://astralcodexten.substack.com/p/links-for-march",
    "https://astralcodexten.substack.com/p/shilling-for-big-mitochondria",
    "https://astralcodexten.substack.com/p/mantic-monday-scoring-rule-controversy",
    "https://astralcodexten.substack.com/p/open-thread-161",
    "https://astralcodexten.substack.com/p/bay-area-plant-based-meat-reviews",
    "https://astralcodexten.substack.com/p/a-modest-proposal-for-republicans",
    "https://astralcodexten.substack.com/p/book-review-fussell-on-class",
    "https://astralcodexten.substack.com/p/mantic-monday-judging-april-covid",
    "https://astralcodexten.substack.com/p/a-look-down-track-b",
    "https://astralcodexten.substack.com/p/open-thread-160",
    "https://astralcodexten.substack.com/p/movie-review-gabriel-over-the-white",
    "https://astralcodexten.substack.com/p/ezra-klein-on-vetocracy",
    "https://astralcodexten.substack.com/p/highlights-from-the-comments-on-cult",
    "https://astralcodexten.substack.com/p/book-review-the-cult-of-smart",
    "https://astralcodexten.substack.com/p/covidvitamin-d-much-more-than-you",
    "https://astralcodexten.substack.com/p/coronavirus-links-discussion-open",
    "https://astralcodexten.substack.com/p/statement-on-new-york-times-article",
    "https://astralcodexten.substack.com/p/the-precision-of-sensory-evidence",
    "https://astralcodexten.substack.com/p/list-of-fictional-cryptocurrencies",
    "https://astralcodexten.substack.com/p/ontology-of-psychiatric-conditions-653",
    "https://astralcodexten.substack.com/p/book-review-why-were-polarized",
    "https://astralcodexten.substack.com/p/metaculus-monday-2821",
    "https://astralcodexten.substack.com/p/open-thread-159",
    "https://astralcodexten.substack.com/p/journalism-and-legible-expertise",
    "https://astralcodexten.substack.com/p/webmd-and-the-tragedy-of-legible",
    "https://astralcodexten.substack.com/p/book-review-contest-final-rules",
    "https://astralcodexten.substack.com/p/ontology-of-psychiatric-conditions-34e",
    "https://astralcodexten.substack.com/p/riddle-of-the-sphinx-ii-sustained",
    "https://astralcodexten.substack.com/p/metaculus-monday",
    "https://astralcodexten.substack.com/p/open-thread-158",
    "https://astralcodexten.substack.com/p/technocracy-zilla-origins",
    "https://astralcodexten.substack.com/p/weyl-contra-me-on-technocracy",
    "https://astralcodexten.substack.com/p/contra-weyl-on-technocracy",
    "https://astralcodexten.substack.com/p/ontology-of-psychiatric-conditions",
    "https://astralcodexten.substack.com/p/know-your-amphetamines",
    "https://astralcodexten.substack.com/p/open-thread-157",
    "https://astralcodexten.substack.com/p/logistics",
    "https://astralcodexten.substack.com/p/still-alive",
    "https://astralcodexten.substack.com/p/youre-probably-wondering-why-ive",
]


def check_mentions(api, keywords, since_id):
    logger.info("Retrieving mentions")
    new_since_id = since_id
    for tweet in tweepy.Cursor(api.mentions_timeline, since_id=since_id).items():
        new_since_id = max(tweet.id, new_since_id)
        # logger.info(tweet)
        if tweet.in_reply_to_status_id is None:
            logger.error(f"not a reply")
            continue
        if tweet.user.screen_name != "__justplaying":
            logger.error(f"i only answer to alice")
            continue
        if any(keyword in tweet.text.lower() for keyword in keywords):
            logger.info(f"dispensing punishment")

            api.update_status(
                status="@elymitra_ " + random.sample(acx_articles, 1)[0],
                in_reply_to_status_id=tweet.id,
                auto_populate_reply_metadata=True,
            )
    return new_since_id


def main():
    api = create_api()
    my_latest_tweet = api.user_timeline(screen_name="elybot_", count=1)[0]
    since_id = my_latest_tweet.id
    while True:
        since_id = check_mentions(api, ["!punish"], since_id)
        logger.info("Waiting...")
        time.sleep(30)


if __name__ == "__main__":
    main()
